runtime: nodejs14

env_variables:
  DATABASE_URL: "postgresql://postgres:gGmemvqn4ufqs33G@34.94.128.162:5432/api?sslmode=disable" #"postgresql://postgres:gGmemvqn4ufqs33G@localhost/api?host=/cloudsql/apiapi-api-database"
  PORT: 8080

