name: Deploy to App Engine

on:
  push:
    branches:
      - "master"

jobs:
  deploy_to_app_engine:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Install Prisma
        run: npm install @prisma/cli -D
      - name: Generate Prisma Client
        run: prisma generate
        env:
          DATABASE_URL: "postgresql://postgres:gGmemvqn4ufqs33G@localhost/api?host=/cloudsql/apiapi-api-database"
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build-ts
      - run: gcloud app deploy
